# app.yaml
name: databricks-demo-app
command:
  - "npm"
  - "start"
install:
  - "npm"
  - "install"
  - "npm"
  - "run"
  - "build"

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "e809614608ea2cfd"
  - name: "SOME_OTHER_VAR"
    value: "some_value"